apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubescale-deployment
  labels:
    app: kubescale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubescale
  template:
    metadata:
      labels:
        app: kubescale
    spec:
      containers:
        - name: kubescale
          image: 593814964617.dkr.ecr.ap-south-1.amazonaws.com/kubescale:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kubescale-service
spec:
  selector:
    app: kubescale
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
