name: KubeScale CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_URI=593814964617.dkr.ecr.ap-south-1.amazonaws.com/kubescale:latest
          docker build -t $IMAGE_URI ./k8s/html
          docker push $IMAGE_URI

      - name: Update Kubernetes manifests with new image
        run: |
          sed -i "s|image: .*|image: 593814964617.dkr.ecr.ap-south-1.amazonaws.com/kubescale:latest|" ./k8s/nginx-blue.yaml

      - name: Apply Kubernetes manifests
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name kubescale-cluster
          kubectl apply -f ./k8s/
